### ISSUE TITLE
Update Kubernetes Version in azuredeploy.json

### ISSUE THREAD

**Issue by evmoreno** [microsoft/MCW-Cloud-native-applications#133]
Hands-on lab/arm/azuredeploy.json

deprecated    "kubernetesVersion": "1.10.12"

**Comment by DawnmarieDesJardins** [comment]
Hi @evmoreno 
I just merged a December test/fix for this workshop.  Can you please check to see if that merge has resolved your issue?  If not, I'll have one of our authors review it.
Thanks - Dawnmarie

**Comment by wely** [comment]
@DawnmarieDesJardins , not yet fixed since https://github.com/microsoft/MCW-Cloud-native-applications/blob/master/Hands-on%20lab/arm/azuredeploy.json is still not yet updated to Dec. It still show for the 26 Sept.

**Comment by DawnmarieDesJardins** [comment]
@wely - please check again.  Everything I see is dated December.  You may need to clear history and/or cookies to get the latest version.

**Comment by wely** [comment]
@DawnmarieDesJardins FYI:
![image](https://user-images.githubusercontent.com/1658657/71614124-edc6fb80-2be4-11ea-99b2-2ffea1acacfa.png)
